---


# Create ETCD data directory
- name: R2.1.1 Create ETCD data directory
  ansible.builtin.file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: '0700'

- name: R2.1.2 Create ETCD config directory
  ansible.builtin.file:
    path: "{{ etcd_config_dir }}"
    state: directory
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: '0700'


# Download and install ETCD binary from Google Storage
- name: R2.2.0 Create temp unarchive dir for etcd
  ansible.builtin.file:
    path: "{{ etcd_unarchive_dir }}"
    state: directory
    mode: '0755'

- name: R2.2.1 Download ETCD binary
  ansible.builtin.get_url:
    url: "{{ etcd_download_url }}"
    dest: "{{ etcd_download_tmp }}"
    mode: '0644'
  when: etcd_download_url is defined

- name: R2.2.2 Unarchive ETCD binary
  ansible.builtin.unarchive:
    src: "{{ etcd_download_tmp }}"
    dest: "{{ etcd_unarchive_dir }}"
    remote_src: yes
    extra_opts: ["--strip-components=1", "--no-same-owner"]
  when: etcd_download_url is defined

- name: R2.2.3 Copy etcd to bin dir
  ansible.builtin.copy:
    src: "{{ etcd_unarchive_dir }}/etcd"
    dest: "{{ etcd_bin_dir }}/etcd"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  when: etcd_download_url is defined

- name: R2.2.4 Copy etcdctl to bin dir
  ansible.builtin.copy:
    src: "{{ etcd_unarchive_dir }}/etcdctl"
    dest: "{{ etcd_bin_dir }}/etcdctl"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  when: etcd_download_url is defined

- name: R2.2.5 Copy etcdutl to bin dir
  ansible.builtin.copy:
    src: "{{ etcd_unarchive_dir }}/etcdutl"
    dest: "{{ etcd_bin_dir }}/etcdutl"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  when: etcd_download_url is defined


# Configure ETCD
- name: R2.3 Configure ETCD
  ansible.builtin.template:
    src: etcd.conf.j2
    dest: "{{ etcd_config_dir }}/etcd.conf.yml"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: '0644'
  notify: restart etcd

# Deploy ETCD systemd service file
- name: R2.4 Deploy ETCD systemd service file
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

# Ensure systemd is reloaded after service file change
- name: R2.5 Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'

# Start and enable ETCD service
- name: R2.6 Start and enable ETCD service
  ansible.builtin.service:
    name: etcd
    state: started
    enabled: yes