---
# Install Patroni
- name: R4.1 Install Patroni and dependencies 
  ansible.builtin.package:
    name:
      - patroni
      - patroni-etcd
    state: present
    enablerepo: pgdg-rhel9-extras
  become: yes

# Ensure Patroni config directory exists
- name: R4.2 Ensure Patroni config directory exists
  ansible.builtin.file:
    path: "{{ patroni_config_dir }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: '0755'
  become: yes

# Configure Patroni
- name: R4.3 Configure Patroni
  ansible.builtin.template:
    src: patroni.yml.j2
    dest: "{{ patroni_config_dir }}/patroni.yml"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: '0600'
  become: yes

# Disable default PostgreSQL service to avoid conflict with Patroni
- name: R4.4 Disable and stop default PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql-{{ postgresql_version }}
    enabled: no
    state: stopped
  become: yes

# Start and enable Patroni service
- name: R4.5 Start and enable Patroni service
  ansible.builtin.service:
    name: patroni
    state: started
    enabled: yes
  become: yes

# Cấu hình patronictl
- name: R4.6 Tạo file cấu hình patronictl
  ansible.builtin.template:
    src: patronictl.yaml.j2
    dest: "{{ patroni_config_dir }}/patronictl.yaml"
    owner: root
    group: root
    mode: '0644'
  become: yes