NODE_ID: 1

ENV: prod

server:
  port: 8084
spring:
  application:
    name: alarm-service
  datasource-alarm:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://dmz-trading-db01:3306/alarm
    username: alarm
    password: 'x*)8]wv298UPUKFs'
  datasource-datafeed:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://dmz-trading-db01:3306/finn_data?serverTimezone=Asia/Ho_Chi_Minh
    username: admin
    password: '8k0d3tUGeVIf/0J/'
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    show-sql: false
  jackson:
    deserialization:
      ACCEPT_FLOAT_AS_INT: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mariadb://dmz-trading-db01:3306/mysql
    schemas: alarm
    user: admin
    password: '8k0d3tUGeVIf/0J/'
  redis:
    type: single
    host: localhost
    port: 6379
    username: default
    password: GnmRuAjJMQzglLx
  schedule:
    enabled: true
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    groups-order: desc
    url: /swagger/api-docs
    enabled: true
api:
  server:
    url: https://jbsv-wts.grooo.com.vn
    description:
  info:
    title: JBSV-Alarm API
    description: Documentation JBSV-Alarm API v${api.info.version}
    version: 1.0

logbook:
  include:
    - /api/**
    - /internal/**
  exclude:
    - /swagger-ui.html
    - /actuator/health
  format:
    style: splunk
  strategy: default
logging:
  level:
    root: WARN
    #org.springframework.web: DEBUG
    org.zalando.logbook: TRACE
    com.ftl: ERROR
    com.jbsv: INFO
  file:
    #path: D:\\JBSV\\channel\\logs
    path: /app/logs

app:
  kafkaUrl: localhost:9092
  clusterId: ${spring.application.name}
  kafkaTimeout: 15000
  nodeId: ${NODE_ID}
  instanceId: ${spring.application.name}_${app.nodeId}_1
  env: ${ENV}

jbsv:
  integrate:
    wts:
      domain: localhost:8888
      ssl: false
      timeoutMillis: 30000
      readTimeoutMillis: 30000
      connectTimeoutMillis: 30000
