NODE_ID: 1

ENV: prod

server:
  port: 8088
#  forward-headers-strategy: framework
spring:
#  config:
#    import: 'optional:consul:'
  application:
    name: banner-service
  jackson:
    time-zone: 'Asia/Ho_Chi_Minh'
  datasource:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://dmz-trading-db01:3306/banner
    username: banner
    password: 'p8keW)]zm!*F99z*'
    #url: jdbc:mariadb://lb:3306/banner
    #username: banner
    #password: 'SG4DzFiKEk4[zN)U'
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    show-sql: true
#  jackson:
#    time-zone: Asia/Ho_Chi_Minh
#    date-format: yyyy-MM-dd HH:mm:ss
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mariadb://dmz-trading-db01:3306/mysql
    schemas: banner
    user: admin
    password: '8k0d3tUGeVIf/0J/'
  redis:
    type: single
    host: localhost
    port: 6379
    username: default
    password: GnmRuAjJMQzglLx
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    groups-order: desc
    url: /swagger/api-docs
    enabled: true
api:
  server:
    url: https://jbsv-wts.grooo.com.vn
    description:
  info:
    title: JBSV-Banner API
    description: Documentation JBSV-Banner API v${api.info.version}
    version: 1.0

logbook:
  include:
    - /api/**
    - /internal/**
  exclude:
    - /swagger-ui.html
    - /actuator/health
  format:
    style: splunk
  strategy: default
logging:
  level:
    root: WARN
  #  org.springframework.web: DEBUG
    org.zalando.logbook: TRACE
    com.ftl: INFO
  file:
    path: /app/logs

app:
  kafkaUrl: localhost:9092
  clusterId: ${spring.application.name}
  kafkaTimeout: 15000
  nodeId: ${NODE_ID}
  instanceId: ${spring.application.name}_${app.nodeId}_1
  env: ${ENV}

management:
  endpoints:
    web:
      exposure:
        include: "*"
