NODE_ID: 1
ENV: prod

server:
  port: 8082
#  forward-headers-strategy: framework
spring:
  application:
    name: event-service
  jackson:
    time-zone: 'Asia/Ho_Chi_Minh'
  datasource:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://dmz-trading-db01:3306/event?useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh
    username: event
    password: '2XH.a4a)9[(G!aCC'
    #url: jdbc:mariadb://lb:3306/event
    #username: event
    #password: '5mnBlHANbEv[0vJa'
  datasource-secondary:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://dmz-trading-db01:3306/notification?useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh
    username: notification
    password: 'vp3ubcD-aTFi!aor'
  datasource-common:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://dmz-trading-db01:3306/common?useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh
    username: common
    password: 'YqtvZu_50/)YUnG0'
  datasource-alarm:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://dmz-trading-db01:3306/alarm
    username: alarm
    password: 'x*)8]wv298UPUKFs'
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
      jdbc:
        time-zone: 'Asia/Ho_Chi_Minh'
      dialect: org.hibernate.dialect.MariaDB103Dialect
      format_sql: true
    show-sql: true
  #  jackson:
  #    time-zone: Asia/Ho_Chi_Minh
  #    date-format: yyyy-MM-dd HH:mm:ss
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mariadb://dmz-trading-db01:3306/mysql
    schemas: event
    user: admin
    password: '8k0d3tUGeVIf/0J/'
  redis:
    type: single
    host: localhost
    port: 6379
    username: default
    password: GnmRuAjJMQzglLx
  schedule:
    enabled: true
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    groups-order: desc
    url: /swagger/api-docs

logbook:
  include:
    - /api/**
    - /internal/**
  exclude:
    - /swagger-ui.html
    - /actuator/health
  format:
    style: splunk
  strategy: default
logging:
  level:
    root: WARN
    #    org.springframework.web: DEBUG
    org.zalando.logbook: TRACE
    com.jbsv: INFO
    com.ftl: WARN
  file:
    path: /app/logs
  path: /app/logs

app:
  kafkaUrl: localhost:9092
  clusterId: ${spring.application.name}
  kafkaTimeout: 15000
  nodeId: ${NODE_ID}
  instanceId: ${spring.application.name}_${app.nodeId}_1
  env: ${ENV}

api:
  server:
    url: https://jbsv-wts.grooo.com.vn
    description}:
  info:
    title: JBSV-Event API
    description: Documentation JBSV-Event API v${api.info.version}
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"



jbsv:
  integrate:
    core-admin:
      domain : 127.0.0.1:8095
      enabled: true
      username: 'Admin'
      password: '123456'
      timeoutMillis: 30000
      readTimeoutMillis: 30000
      connectTimeoutMillis: 30000
