NODE_ID: 1

ENV: prod

server:
  port: 8085
#  forward-headers-strategy: framework
spring:
  #  config:
  #    import: 'optional:consul:'
  application:
    name: market-data-service
  datasource:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://192.168.44.11:3306/finn_data?serverTimezone=Asia/Ho_Chi_Minh
    username: admin
    password: '8k0d3tUGeVIf/0J/'
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time-zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
      show-sql: false
#  jackson:
#    time-zone: Asia/Ho_Chi_Minh
#    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    type: single
    host: localhost
    port: 6379
    username: default
    password: GnmRuAjJMQzglLx

#  redis:
#    type: cluster
#    port: 26379
#    password: 'GnmRuAjJMQzglLx'
#    sentinel:
#      master: mymaster
#      nodes:
#        - trading
#    lettuce:
#      shutdown-timeout: 200ms

  schedule:
    enabled: true
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
    groups-order: desc
    url: /swagger/api-docs
    enabled: true
api:
  server:
    url: https://jbsv-wts.grooo.com.vn
    description:
  info:
    title: JBSV-Market-Data API
    description: Documentation JBSV-Market-Data API v${api.info.version}
    version: 1.0

logbook:
  include:
    - /api/**
    - /internal/**
  exclude:
    - /swagger-ui.html
    - /actuator/health
  format:
    style: splunk
  strategy: default
logging:
  level:
    root: WARN
    #    org.springframework.web: DEBUG
    org.zalando.logbook: TRACE
    com.ftl: ERROR
    com.jbsv: INFO
  file:
    path: /app/logs

app:
  kafkaUrl: localhost:9092
  clusterId: ${spring.application.name}
  kafkaTimeout: 15000
  nodeId: ${NODE_ID}
  instanceId: ${spring.application.name}_${app.nodeId}_1
  env: ${ENV}

jbsv:
  integrate:
    wts:
      domain: localhost:8888
      ssl: false
      timeoutMillis: 30000
      readTimeoutMillis: 30000
      connectTimeoutMillis: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"

mongodb:
  host: localhost
  port: 27017
  database: grooo-market
  username: market
  password: s59PFm)u4WNHrZge
  re_stock_change_date:
