NODE_ID: 1

ENV: prod

server:
  port: 8086
#  forward-headers-strategy: framework
spring:
  #  config:
  #    import: 'optional:consul:'
  application:
    name: stock-detail-service
  datasource:
    driverClassName: "org.mariadb.jdbc.Driver"
    url: jdbc:mariadb://localhost:3306/finn_data?serverTimezone=Asia/Ho_Chi_Minh
    username: admin
    password: '8k0d3tUGeVIf/0J/'
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        #          dialect: org.hibernate.dialect.MariaDB103Dialect
#        format_sql: true
    show-sql: false
  redis:
    type: single
    host: localhost
    port: 6379
    username: default
    password: GnmRuAjJMQzglLx
#  redis:
#    type: cluster
#    port: 26379
#    password: 'GnmRuAjJMQzglLx'
#    sentinel:
#      master: mymaster
#      nodes:
#        - trading
#    lettuce:
#      shutdown-timeout: 200ms
  schedule:
    enabled: true

logging:
  level:
    root: WARN
  #  org.springframework.web: DEBUG
    org.zalando.logbook: TRACE
    com.ftl: WARN
    com.jbsv.stock: INFO
  file:
    path: /app/logs

app:
  kafkaUrl: localhost:9092
  clusterId: ${spring.application.name}
  kafkaTimeout: 15000
  nodeId: ${NODE_ID}
  instanceId: ${spring.application.name}_${app.nodeId}_1
  env: ${ENV}

management:
  endpoints:
    web:
      exposure:
        include: "*"
